2022-03-11 05:01:22,702 INFO    Thread-32 :46628 [wandb_setup.py:_flush():69] setting env: {'project': 'L-tune', 'entity': 'wtmlon', 'root_dir': '/lt/DART', 'run_id': 'n5pxqen5', 'sweep_param_path': '/lt/DART/wandb/sweep-fm5wnjye/config-n5pxqen5.yaml', 'sweep_id': 'fm5wnjye'}
2022-03-11 05:01:22,703 INFO    Thread-32 :46628 [wandb_init.py:_log_setup():336] Logging user logs to /lt/DART/wandb/run-20220311_050122-n5pxqen5/logs/debug.log
2022-03-11 05:01:22,703 INFO    Thread-32 :46628 [wandb_init.py:_log_setup():337] Logging internal logs to /lt/DART/wandb/run-20220311_050122-n5pxqen5/logs/debug-internal.log
2022-03-11 05:01:22,704 INFO    Thread-32 :46628 [wandb_init.py:init():369] calling init triggers
2022-03-11 05:01:22,704 INFO    Thread-32 :46628 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 21, 'task': 'SST-2', 'weight_decay': 0.05, 'x_input': 'mix'}
config: {}
2022-03-11 05:01:22,704 INFO    Thread-32 :46628 [wandb_init.py:init():418] starting backend
2022-03-11 05:01:22,704 INFO    Thread-32 :46628 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-11 05:01:22,710 INFO    Thread-32 :46628 [backend.py:ensure_launched():132] starting backend process...
2022-03-11 05:01:22,722 INFO    Thread-32 :46628 [backend.py:ensure_launched():136] started backend process with pid: 47315
2022-03-11 05:01:22,724 INFO    Thread-32 :46628 [wandb_init.py:init():423] backend started and connected
2022-03-11 05:01:22,725 INFO    Thread-32 :46628 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 21, 'task': 'SST-2', 'weight_decay': 0.05, 'x_input': 'mix'}
2022-03-11 05:01:22,726 INFO    Thread-32 :46628 [wandb_init.py:init():465] updated telemetry
2022-03-11 05:01:22,727 INFO    Thread-32 :46628 [wandb_init.py:init():484] communicating current version
2022-03-11 05:01:27,728 INFO    Thread-32 :46628 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-11 05:01:28,899 INFO    Thread-32 :46628 [wandb_init.py:init():522] starting run threads in backend
2022-03-11 05:01:33,908 INFO    Thread-32 :46628 [wandb_run.py:_console_start():1565] atexit reg
2022-03-11 05:01:33,910 INFO    Thread-32 :46628 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2022-03-11 05:01:33,910 INFO    Thread-32 :46628 [wandb_run.py:_redirect():1417] Redirecting console.
2022-03-11 05:01:33,912 ERROR   Thread-32 :46628 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/root/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-03-11 05:01:33,913 INFO    Thread-32 :46628 [wandb_init.py:init():546] run started, returning control to user process
2022-03-11 05:01:53,214 INFO    Thread-37 :46628 [wandb_setup.py:_flush():69] setting env: {'project': 'L-tune', 'entity': 'wtmlon', 'root_dir': '/lt/DART', 'run_id': 'wa7hp057', 'sweep_param_path': '/lt/DART/wandb/sweep-fm5wnjye/config-wa7hp057.yaml', 'sweep_id': 'fm5wnjye'}
2022-03-11 05:01:53,215 INFO    Thread-37 :46628 [wandb_init.py:_log_setup():336] Logging user logs to /lt/DART/wandb/run-20220311_050153-wa7hp057/logs/debug.log
2022-03-11 05:01:53,216 INFO    Thread-37 :46628 [wandb_init.py:_log_setup():337] Logging internal logs to /lt/DART/wandb/run-20220311_050153-wa7hp057/logs/debug-internal.log
2022-03-11 05:01:53,216 INFO    Thread-37 :46628 [wandb_init.py:init():369] calling init triggers
2022-03-11 05:01:53,216 INFO    Thread-37 :46628 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 21, 'task': 'SST-2', 'weight_decay': 0.1, 'x_input': 'mix'}
config: {}
2022-03-11 05:01:53,217 INFO    Thread-37 :46628 [wandb_init.py:init():418] starting backend
2022-03-11 05:01:53,217 INFO    Thread-37 :46628 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-11 05:01:53,223 INFO    Thread-37 :46628 [backend.py:ensure_launched():132] starting backend process...
2022-03-11 05:01:53,235 INFO    Thread-37 :46628 [backend.py:ensure_launched():136] started backend process with pid: 47404
2022-03-11 05:01:53,237 INFO    Thread-37 :46628 [wandb_init.py:init():423] backend started and connected
2022-03-11 05:01:53,238 INFO    Thread-37 :46628 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 21, 'task': 'SST-2', 'weight_decay': 0.1, 'x_input': 'mix'}
2022-03-11 05:01:53,239 INFO    Thread-37 :46628 [wandb_init.py:init():465] updated telemetry
2022-03-11 05:01:53,240 INFO    Thread-37 :46628 [wandb_init.py:init():484] communicating current version
2022-03-11 05:01:58,241 INFO    Thread-37 :46628 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-11 05:01:59,459 INFO    Thread-37 :46628 [wandb_init.py:init():522] starting run threads in backend
2022-03-11 05:02:04,477 ERROR   Thread-37 :46628 [wandb_init.py:init():770] error
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 525, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 799, in communicate_run_start
    result = self._communicate(rec)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 537, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/root/anaconda3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/root/anaconda3/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
Exception
2022-03-11 05:02:06,485 INFO    Thread-37 :46628 [wandb_run.py:finish():1208] finishing run wtmlon/L-tune/n5pxqen5
